dist: bionic
language: go
services: docker

branches:
  only:
    - master

go:
  - "1.12"
  - "1.13"
env:
  global:
    - GO111MODULE=on

install:
  - go mod download
  - go build ./...

before_script:
  - docker-compose up -d
  - echo 'replace github.com/at-wat/mqtt-go => ../' >> paho/go.mod

script:
  - go vet -tags integration ./...
  - |
    go test $(go list ./... | grep -v examples) \
      -v \
      -tags integration \
      -race -coverprofile=coverage.txt -covermode=atomic
  - (cd paho; go vet ./...)

after_script:
  - docker-compose down

after_success:
  - bash <(curl -s https://codecov.io/bash)
