dist: bionic
language: go
services: docker

branches:
  only:
    - master

go:
  - "1.12"
  - "1.13"
env:
  global:
    - GO111MODULE=on

install:
  - go mod download
  - go build ./...

before_script:
  - docker-compose up -d

script:
  - go vet ./...
  - go test $(go list ./... | grep -v examples) -tags integration -race -coverprofile=coverage.txt -covermode=atomic

after_script:
  - docker-compose down

after_success:
  - bash <(curl -s https://codecov.io/bash)
