version: '2'
services:
  mosquitto:
    image: eclipse-mosquitto:1.6
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./integration/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
