name: go-mod-fix
on:
  push:
    branches:
      - renovate/*

jobs:
  go-mod-fix:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: fix
        uses: at-wat/go-sum-fix-action@v0
        with:
          go_mod_paths: ./
          git_user: Atsushi Watanabe
          git_email: atsushi.w@ieee.org
          github_token: ${{ secrets.GO_SUM_FIX_GITHUB_TOKEN }}
          commit_style: squash
          push: force
